# Generated by Django 5.1.2 on 2024-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('average_price', models.IntegerField()),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
    ]
