# Generated by Django 5.1.2 on 2024-12-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelos',
            new_name='Modelos_nexu',
        ),
    ]
